/* nn_predict.c -- drone direction neural network inference
 * auto-generated by export_to_c.py
 * Architecture : 9216 -> 64 (ReLU) -> 4 (argmax)
 * Classes      : 1=LEFT  2=CENTRE  3=RIGHT  4=TURN
 * Compile: gcc -O2 nn_predict.c -o test_nn -lm
 */

#include "nn_predict.h"
#include "model_weights.h"

/* BGR to YUV (BT.601, matches OpenCV COLOR_BGR2YUV) */
static void bgr_to_yuv(unsigned char b, unsigned char g, unsigned char r,
                       float *Y, float *U, float *V)
{
    float rf=r/255.0f, gf=g/255.0f, bf=b/255.0f;
    *Y =  0.299f*rf + 0.587f*gf + 0.114f*bf;
    *U = -0.14713f*rf - 0.28886f*gf + 0.436f*bf + 0.5f;
    *V =  0.615f*rf  - 0.51499f*gf - 0.10001f*bf + 0.5f;
    if (*Y<0.f)*Y=0.f; if (*Y>1.f)*Y=1.f;
    if (*U<0.f)*U=0.f; if (*U>1.f)*U=1.f;
    if (*V<0.f)*V=0.f; if (*V>1.f)*V=1.f;
}

/* Bilinear resize + YUV -> flat feature vector */
static void extract_features(const unsigned char *img_bgr,
                             int src_w, int src_h, float *out)
{
    float sx=(float)src_w/NN_IMG_W, sy=(float)src_h/NN_IMG_H;
    for (int dy=0; dy<NN_IMG_H; dy++) {
        float src_y=(dy+0.5f)*sy-0.5f;
        int y0=(int)src_y, y1=y0+1;
        float fy=src_y-y0;
        if (y0<0) y0=0; if (y1>=src_h) y1=src_h-1;
        for (int dx=0; dx<NN_IMG_W; dx++) {
            float src_x=(dx+0.5f)*sx-0.5f;
            int x0=(int)src_x, x1=x0+1;
            float fx=src_x-x0;
            if (x0<0) x0=0; if (x1>=src_w) x1=src_w-1;
            const unsigned char *p00=img_bgr+(y0*src_w+x0)*3;
            const unsigned char *p01=img_bgr+(y0*src_w+x1)*3;
            const unsigned char *p10=img_bgr+(y1*src_w+x0)*3;
            const unsigned char *p11=img_bgr+(y1*src_w+x1)*3;
            float w00=(1-fx)*(1-fy),w01=fx*(1-fy),w10=(1-fx)*fy,w11=fx*fy;
            float b=w00*p00[0]+w01*p01[0]+w10*p10[0]+w11*p11[0];
            float g=w00*p00[1]+w01*p01[1]+w10*p10[1]+w11*p11[1];
            float r=w00*p00[2]+w01*p01[2]+w10*p10[2]+w11*p11[2];
            float Y,U,V;
            bgr_to_yuv((unsigned char)b,(unsigned char)g,(unsigned char)r,&Y,&U,&V);
            int base=(dy*NN_IMG_W+dx)*3;
            out[base+0]=Y; out[base+1]=U; out[base+2]=V;
        }
    }
}

/* Forward pass */
int nn_predict(const unsigned char *img_bgr, int width, int height)
{
    float x[NN_INPUT_SIZE];
    extract_features(img_bgr, width, height, x);

    /* Hidden layer: h = ReLU(W1 @ x + b1) */
    float h[NN_HIDDEN_SIZE];
    for (int i=0; i<NN_HIDDEN_SIZE; i++) {
        float sum=NN_b1[i];
        const float *w=NN_W1+i*NN_INPUT_SIZE;
        for (int j=0; j<NN_INPUT_SIZE; j++) sum+=w[j]*x[j];
        h[i]=sum>0.f?sum:0.f;
    }

    /* Output layer: argmax(W2 @ h + b2) */
    int best=0; float best_score=-1e30f;
    for (int i=0; i<NN_OUTPUT_SIZE; i++) {
        float sum=NN_b2[i];
        const float *w=NN_W2+i*NN_HIDDEN_SIZE;
        for (int j=0; j<NN_HIDDEN_SIZE; j++) sum+=w[j]*h[j];
        if (sum>best_score) { best_score=sum; best=i; }
    }
    return NN_CLASSES[best];
}
