/* nn_predict.h -- drone direction neural network inference
 * auto-generated by export_to_c.py
 *
 * Classes: 1=LEFT  2=CENTRE  3=RIGHT  4=TURN
 * Turn-around label: 4
 */
#ifndef NN_PREDICT_H
#define NN_PREDICT_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Predict direction from a BGR image.
 * img_bgr : raw BGR pixel data, row-major, 3 bytes per pixel
 * width   : image width in pixels
 * height  : image height in pixels
 * Returns : 1=LEFT  2=CENTRE  3=RIGHT  4=TURN
 */
int nn_predict(const unsigned char *img_bgr, int width, int height);

#ifdef __cplusplus
}
#endif

#endif /* NN_PREDICT_H */
