"""
export_to_c.py
==============
Exports the trained numpy model to a standalone C implementation.

Generates two files:
  model_weights.h   — all weights as static float arrays
  nn_predict.c      — self-contained inference function
  nn_predict.h      — header to include in your drone code

The C inference function signature:
  int nn_predict(const unsigned char *img_bgr, int width, int height);
  Returns: 1-8 (strip number or 8 = turn around)

The C code has zero dependencies beyond standard C math (no OpenCV needed
for the resize — uses a simple bilinear resize included inline).
"""

import numpy as np
import os

# ── Config ────────────────────────────────────────────────────────────────────
MODEL_DIR  = r'C:\Users\neytc\Documents\TU_Delft\lecture_notes\mav\MAV_CW\DEVELOPMENT\Python\neural_network\model'
OUTPUT_DIR = MODEL_DIR   # write C files alongside the model

IMG_W = 64
IMG_H = 48

# ══════════════════════════════════════════════════════════════════════════════

def array_to_c(name, arr, indent=0):
    """Convert a numpy array to a C static float array declaration."""
    flat  = arr.flatten().astype(np.float32)
    lines = []
    sp    = ' ' * indent
    lines.append(f'{sp}static const float {name}[{len(flat)}] = {{')
    # 8 values per line
    for i in range(0, len(flat), 8):
        chunk = flat[i:i+8]
        vals  = ', '.join(f'{v:.8f}f' for v in chunk)
        comma = ',' if i + 8 < len(flat) else ''
        lines.append(f'{sp}    {vals}{comma}')
    lines.append(f'{sp}}};')
    return '\n'.join(lines)


def main():
    # Load model
    W1      = np.load(os.path.join(MODEL_DIR, 'model_W1.npy')).astype(np.float32)
    b1      = np.load(os.path.join(MODEL_DIR, 'model_b1.npy')).astype(np.float32)
    W2      = np.load(os.path.join(MODEL_DIR, 'model_W2.npy')).astype(np.float32)
    b2      = np.load(os.path.join(MODEL_DIR, 'model_b2.npy')).astype(np.float32)
    classes = np.load(os.path.join(MODEL_DIR, 'model_classes.npy')).astype(np.int32)

    hidden_size = W1.shape[0]   # 64
    n_feat      = W1.shape[1]   # 9216
    n_cls       = W2.shape[0]   # 8

    print(f'W1: {W1.shape}   b1: {b1.shape}')
    print(f'W2: {W2.shape}   b2: {b2.shape}')
    print(f'classes: {classes}')
    print(f'Input features: {n_feat}  ({IMG_W}x{IMG_H}x3)')

    # ── 1. model_weights.h ────────────────────────────────────────────────────
    weights_h = os.path.join(OUTPUT_DIR, 'model_weights.h')
    with open(weights_h, 'w') as f:
        f.write('/* model_weights.h — auto-generated by export_to_c.py */\n')
        f.write('/* DO NOT EDIT MANUALLY */\n\n')
        f.write('#ifndef MODEL_WEIGHTS_H\n#define MODEL_WEIGHTS_H\n\n')
        f.write(f'#define NN_INPUT_SIZE   {n_feat}\n')
        f.write(f'#define NN_HIDDEN_SIZE  {hidden_size}\n')
        f.write(f'#define NN_OUTPUT_SIZE  {n_cls}\n')
        f.write(f'#define NN_IMG_W        {IMG_W}\n')
        f.write(f'#define NN_IMG_H        {IMG_H}\n\n')

        # Class labels
        f.write(f'static const int NN_CLASSES[{n_cls}] = {{')
        f.write(', '.join(str(c) for c in classes))
        f.write('};\n\n')

        # Weight arrays
        f.write('/* W1: hidden x input */\n')
        f.write(array_to_c('NN_W1', W1))
        f.write('\n\n/* b1: hidden */\n')
        f.write(array_to_c('NN_b1', b1))
        f.write('\n\n/* W2: output x hidden */\n')
        f.write(array_to_c('NN_W2', W2))
        f.write('\n\n/* b2: output */\n')
        f.write(array_to_c('NN_b2', b2))
        f.write('\n\n#endif /* MODEL_WEIGHTS_H */\n')

    print(f'\nWritten: {weights_h}')
    size_kb = os.path.getsize(weights_h) / 1024
    print(f'  Size: {size_kb:.0f} KB')

    # ── 2. nn_predict.h ───────────────────────────────────────────────────────
    predict_h = os.path.join(OUTPUT_DIR, 'nn_predict.h')
    with open(predict_h, 'w', encoding='utf-8') as f:
        f.write(
'''/* nn_predict.h — drone direction neural network inference
 * auto-generated by export_to_c.py
 *
 * Include this in your drone code:
 *   #include "nn_predict.h"
 *
 * Then call:
 *   int direction = nn_predict(img_bgr, width, height);
 *   // Returns 1-7 (strip) or 8 (turn around)
 */
#ifndef NN_PREDICT_H
#define NN_PREDICT_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * Predict direction from a BGR image.
 *
 * img_bgr  : pointer to raw BGR pixel data, row-major, 3 bytes per pixel
 * width    : image width in pixels
 * height   : image height in pixels
 *
 * Returns  : 1-7 (fly toward strip N) or 8 (turn around)
 */
int nn_predict(const unsigned char *img_bgr, int width, int height);

#ifdef __cplusplus
}
#endif

#endif /* NN_PREDICT_H */
''')
    print(f'Written: {predict_h}')

    # ── 3. nn_predict.c ───────────────────────────────────────────────────────
    predict_c = os.path.join(OUTPUT_DIR, 'nn_predict.c')
    with open(predict_c, 'w', encoding='utf-8') as f:
        f.write(
f'''/* nn_predict.c — drone direction neural network inference
 * auto-generated by export_to_c.py
 *
 * Architecture: {n_feat} -> {hidden_size} (ReLU) -> {n_cls} (argmax)
 * Input       : any size BGR image (bilinear resize to {IMG_W}x{IMG_H} internally)
 * Output      : class label 1-8
 *
 * Zero dependencies — only uses standard C (no OpenCV, no BLAS).
 * Compile with: gcc -O2 -o nn_predict nn_predict.c -lm
 */

#include "nn_predict.h"
#include "model_weights.h"
#include <string.h>  /* memset */

/* ── BGR to YUV conversion (BT.601, same as OpenCV COLOR_BGR2YUV) ─────────── */
static void bgr_to_yuv(unsigned char b, unsigned char g, unsigned char r,
                        float *Y, float *U, float *V)
{{
    float rf = r / 255.0f;
    float gf = g / 255.0f;
    float bf = b / 255.0f;
    *Y =  0.299f*rf  + 0.587f*gf  + 0.114f*bf;
    *U = -0.14713f*rf - 0.28886f*gf + 0.436f*bf + 0.5f;
    *V =  0.615f*rf  - 0.51499f*gf - 0.10001f*bf + 0.5f;
    /* clamp */
    if (*Y < 0.f) *Y = 0.f; if (*Y > 1.f) *Y = 1.f;
    if (*U < 0.f) *U = 0.f; if (*U > 1.f) *U = 1.f;
    if (*V < 0.f) *V = 0.f; if (*V > 1.f) *V = 1.f;
}}

/* ── Bilinear resize + YUV conversion -> flat feature vector ──────────────── */
static void extract_features(const unsigned char *img_bgr, int src_w, int src_h,
                              float *out)  /* out must be NN_INPUT_SIZE floats */
{{
    float scale_x = (float)src_w  / NN_IMG_W;
    float scale_y = (float)src_h  / NN_IMG_H;

    for (int dy = 0; dy < NN_IMG_H; dy++)
    {{
        float src_y = (dy + 0.5f) * scale_y - 0.5f;
        int   y0    = (int)src_y;
        int   y1    = y0 + 1;
        float fy    = src_y - y0;
        if (y0 < 0)      y0 = 0;
        if (y1 >= src_h) y1 = src_h - 1;

        for (int dx = 0; dx < NN_IMG_W; dx++)
        {{
            float src_x = (dx + 0.5f) * scale_x - 0.5f;
            int   x0    = (int)src_x;
            int   x1    = x0 + 1;
            float fx    = src_x - x0;
            if (x0 < 0)      x0 = 0;
            if (x1 >= src_w) x1 = src_w - 1;

            /* 4 neighbouring pixels (B,G,R each) */
            const unsigned char *p00 = img_bgr + (y0*src_w + x0)*3;
            const unsigned char *p01 = img_bgr + (y0*src_w + x1)*3;
            const unsigned char *p10 = img_bgr + (y1*src_w + x0)*3;
            const unsigned char *p11 = img_bgr + (y1*src_w + x1)*3;

            float w00=(1-fx)*(1-fy), w01=fx*(1-fy),
                  w10=(1-fx)*fy,     w11=fx*fy;

            /* Bilinear interpolate each BGR channel */
            float b = w00*p00[0] + w01*p01[0] + w10*p10[0] + w11*p11[0];
            float g = w00*p00[1] + w01*p01[1] + w10*p10[1] + w11*p11[1];
            float r = w00*p00[2] + w01*p01[2] + w10*p10[2] + w11*p11[2];

            /* Convert to YUV */
            float Y, U, V;
            bgr_to_yuv((unsigned char)b, (unsigned char)g, (unsigned char)r,
                       &Y, &U, &V);

            /* Write into output: [Y, U, V] for each pixel, row-major */
            int base = (dy * NN_IMG_W + dx) * 3;
            out[base + 0] = Y;
            out[base + 1] = U;
            out[base + 2] = V;
        }}
    }}
}}

/* ── Neural network forward pass ─────────────────────────────────────────── */
int nn_predict(const unsigned char *img_bgr, int width, int height)
{{
    /* Step 1: extract features */
    float x[NN_INPUT_SIZE];
    extract_features(img_bgr, width, height, x);

    /* Step 2: hidden layer  h = ReLU(W1 @ x + b1) */
    float h[NN_HIDDEN_SIZE];
    for (int i = 0; i < NN_HIDDEN_SIZE; i++)
    {{
        float sum = NN_b1[i];
        const float *w = NN_W1 + i * NN_INPUT_SIZE;
        for (int j = 0; j < NN_INPUT_SIZE; j++)
            sum += w[j] * x[j];
        h[i] = sum > 0.f ? sum : 0.f;  /* ReLU */
    }}

    /* Step 3: output layer  scores = W2 @ h + b2 */
    int   best_idx   = 0;
    float best_score = -1e30f;
    for (int i = 0; i < NN_OUTPUT_SIZE; i++)
    {{
        float sum = NN_b2[i];
        const float *w = NN_W2 + i * NN_HIDDEN_SIZE;
        for (int j = 0; j < NN_HIDDEN_SIZE; j++)
            sum += w[j] * h[j];
        if (sum > best_score)
        {{
            best_score = sum;
            best_idx   = i;
        }}
    }}

    return NN_CLASSES[best_idx];
}}
''')
    print(f'Written: {predict_c}')

    # ── Summary ───────────────────────────────────────────────────────────────
    print(f'''
Done! Three files written to:
  {OUTPUT_DIR}

Files:
  model_weights.h  — weight arrays ({size_kb:.0f} KB as C source)
  nn_predict.h     — function declaration to include in your code
  nn_predict.c     — full inference implementation

Usage in your drone code:
  #include "nn_predict.h"
  ...
  int direction = nn_predict(frame_bgr, frame_width, frame_height);
  /* direction is 1-7 (strip) or 8 (turn around) */

Compile test:
  gcc -O2 -o test_nn nn_predict.c -lm

The function takes any image size — it resizes internally to {IMG_W}x{IMG_H}.
No OpenCV or external libraries needed.
''')


if __name__ == '__main__':
    main()