"""
export_to_c.py
==============
Exports the trained numpy model to a standalone C implementation.
Works for any label mode (3strip, 5strip, 5merged) automatically.

Generates:
  model_weights.h  — all weights as static float arrays
  nn_predict.h     — function declaration
  nn_predict.c     — self-contained inference (no OpenCV needed)

Usage in drone code:
  #include "nn_predict.h"
  int direction = nn_predict(frame_bgr, width, height);
"""

import numpy as np
import os

# ── Config ────────────────────────────────────────────────────────────────────
MODEL_DIR  = r'C:\Users\neytc\Documents\TU_Delft\lecture_notes\mav\MAV_CW\DEVELOPMENT\Python\neural_network\model'
OUTPUT_DIR = MODEL_DIR

IMG_W = 64
IMG_H = 48

# Human-readable names per class label — update to match your label mode
# 3strip:  {1:'LEFT', 2:'CENTRE', 3:'RIGHT', 4:'TURN'}
# 5strip:  {1:'S1', 2:'S2', 3:'S3', 4:'S4', 5:'S5', 6:'TURN'}
# 5merged: {1:'LEFT', 2:'CENTRE', 3:'RIGHT', 4:'TURN'}
CLASS_NAMES = {1:'LEFT', 2:'CENTRE', 3:'RIGHT', 4:'TURN'}

# ══════════════════════════════════════════════════════════════════════════════

def array_to_c(name, arr):
    flat  = arr.flatten().astype(np.float32)
    lines = [f'static const float {name}[{len(flat)}] = {{']
    for i in range(0, len(flat), 8):
        chunk = flat[i:i+8]
        vals  = ', '.join(f'{v:.8f}f' for v in chunk)
        comma = ',' if i + 8 < len(flat) else ''
        lines.append(f'    {vals}{comma}')
    lines.append('};')
    return '\n'.join(lines)


def main():
    W1      = np.load(os.path.join(MODEL_DIR, 'model_W1.npy')).astype(np.float32)
    b1      = np.load(os.path.join(MODEL_DIR, 'model_b1.npy')).astype(np.float32)
    W2      = np.load(os.path.join(MODEL_DIR, 'model_W2.npy')).astype(np.float32)
    b2      = np.load(os.path.join(MODEL_DIR, 'model_b2.npy')).astype(np.float32)
    classes = np.load(os.path.join(MODEL_DIR, 'model_classes.npy')).astype(np.int32)

    hidden_size = W1.shape[0]
    n_feat      = W1.shape[1]
    n_cls       = W2.shape[0]

    print(f'W1: {W1.shape}   b1: {b1.shape}')
    print(f'W2: {W2.shape}   b2: {b2.shape}')
    print(f'Classes: {classes.tolist()}')
    print(f'Input  : {n_feat} ({IMG_W}x{IMG_H}x3 YUV)')

    cls_desc  = '  '.join(f'{c}={CLASS_NAMES.get(c, str(c))}' for c in classes)
    turn_label = int(classes[-1])

    # ── model_weights.h ───────────────────────────────────────────────────────
    weights_h = os.path.join(OUTPUT_DIR, 'model_weights.h')
    with open(weights_h, 'w', encoding='utf-8') as f:
        f.write('/* model_weights.h -- auto-generated by export_to_c.py */\n')
        f.write('/* DO NOT EDIT MANUALLY */\n\n')
        f.write('#ifndef MODEL_WEIGHTS_H\n#define MODEL_WEIGHTS_H\n\n')
        f.write(f'/* Classes: {cls_desc} */\n\n')
        f.write(f'#define NN_INPUT_SIZE   {n_feat}\n')
        f.write(f'#define NN_HIDDEN_SIZE  {hidden_size}\n')
        f.write(f'#define NN_OUTPUT_SIZE  {n_cls}\n')
        f.write(f'#define NN_IMG_W        {IMG_W}\n')
        f.write(f'#define NN_IMG_H        {IMG_H}\n')
        f.write(f'#define NN_TURN_LABEL   {turn_label}\n\n')
        f.write(f'static const int NN_CLASSES[{n_cls}] = {{')
        f.write(', '.join(str(c) for c in classes))
        f.write('};\n\n')
        f.write('/* W1: hidden x input */\n')
        f.write(array_to_c('NN_W1', W1))
        f.write('\n\n/* b1: hidden */\n')
        f.write(array_to_c('NN_b1', b1))
        f.write('\n\n/* W2: output x hidden */\n')
        f.write(array_to_c('NN_W2', W2))
        f.write('\n\n/* b2: output */\n')
        f.write(array_to_c('NN_b2', b2))
        f.write('\n\n#endif /* MODEL_WEIGHTS_H */\n')

    size_kb = os.path.getsize(weights_h) / 1024
    print(f'\nWritten: {weights_h}  ({size_kb:.0f} KB)')

    # ── nn_predict.h ──────────────────────────────────────────────────────────
    predict_h = os.path.join(OUTPUT_DIR, 'nn_predict.h')
    with open(predict_h, 'w', encoding='utf-8') as f:
        f.write(f'/* nn_predict.h -- drone direction neural network inference\n')
        f.write(f' * auto-generated by export_to_c.py\n')
        f.write(f' *\n')
        f.write(f' * Classes: {cls_desc}\n')
        f.write(f' * Turn-around label: {turn_label}\n')
        f.write(f' */\n')
        f.write('#ifndef NN_PREDICT_H\n#define NN_PREDICT_H\n\n')
        f.write('#ifdef __cplusplus\nextern "C" {\n#endif\n\n')
        f.write('/*\n')
        f.write(' * Predict direction from a BGR image.\n')
        f.write(' * img_bgr : raw BGR pixel data, row-major, 3 bytes per pixel\n')
        f.write(' * width   : image width in pixels\n')
        f.write(' * height  : image height in pixels\n')
        f.write(f' * Returns : {cls_desc}\n')
        f.write(' */\n')
        f.write('int nn_predict(const unsigned char *img_bgr, int width, int height);\n\n')
        f.write('#ifdef __cplusplus\n}\n#endif\n\n')
        f.write('#endif /* NN_PREDICT_H */\n')
    print(f'Written: {predict_h}')

    # ── nn_predict.c ──────────────────────────────────────────────────────────
    predict_c = os.path.join(OUTPUT_DIR, 'nn_predict.c')
    with open(predict_c, 'w', encoding='utf-8') as f:
        f.write(f'/* nn_predict.c -- drone direction neural network inference\n')
        f.write(f' * auto-generated by export_to_c.py\n')
        f.write(f' * Architecture : {n_feat} -> {hidden_size} (ReLU) -> {n_cls} (argmax)\n')
        f.write(f' * Classes      : {cls_desc}\n')
        f.write(f' * Compile: gcc -O2 nn_predict.c -o test_nn -lm\n')
        f.write(' */\n\n')
        f.write('#include "nn_predict.h"\n')
        f.write('#include "model_weights.h"\n\n')

        f.write('/* BGR to YUV (BT.601, matches OpenCV COLOR_BGR2YUV) */\n')
        f.write('static void bgr_to_yuv(unsigned char b, unsigned char g, unsigned char r,\n')
        f.write('                       float *Y, float *U, float *V)\n{\n')
        f.write('    float rf=r/255.0f, gf=g/255.0f, bf=b/255.0f;\n')
        f.write('    *Y =  0.299f*rf + 0.587f*gf + 0.114f*bf;\n')
        f.write('    *U = -0.14713f*rf - 0.28886f*gf + 0.436f*bf + 0.5f;\n')
        f.write('    *V =  0.615f*rf  - 0.51499f*gf - 0.10001f*bf + 0.5f;\n')
        f.write('    if (*Y<0.f)*Y=0.f; if (*Y>1.f)*Y=1.f;\n')
        f.write('    if (*U<0.f)*U=0.f; if (*U>1.f)*U=1.f;\n')
        f.write('    if (*V<0.f)*V=0.f; if (*V>1.f)*V=1.f;\n')
        f.write('}\n\n')

        f.write('/* Bilinear resize + YUV -> flat feature vector */\n')
        f.write('static void extract_features(const unsigned char *img_bgr,\n')
        f.write('                             int src_w, int src_h, float *out)\n{\n')
        f.write('    float sx=(float)src_w/NN_IMG_W, sy=(float)src_h/NN_IMG_H;\n')
        f.write('    for (int dy=0; dy<NN_IMG_H; dy++) {\n')
        f.write('        float src_y=(dy+0.5f)*sy-0.5f;\n')
        f.write('        int y0=(int)src_y, y1=y0+1;\n')
        f.write('        float fy=src_y-y0;\n')
        f.write('        if (y0<0) y0=0; if (y1>=src_h) y1=src_h-1;\n')
        f.write('        for (int dx=0; dx<NN_IMG_W; dx++) {\n')
        f.write('            float src_x=(dx+0.5f)*sx-0.5f;\n')
        f.write('            int x0=(int)src_x, x1=x0+1;\n')
        f.write('            float fx=src_x-x0;\n')
        f.write('            if (x0<0) x0=0; if (x1>=src_w) x1=src_w-1;\n')
        f.write('            const unsigned char *p00=img_bgr+(y0*src_w+x0)*3;\n')
        f.write('            const unsigned char *p01=img_bgr+(y0*src_w+x1)*3;\n')
        f.write('            const unsigned char *p10=img_bgr+(y1*src_w+x0)*3;\n')
        f.write('            const unsigned char *p11=img_bgr+(y1*src_w+x1)*3;\n')
        f.write('            float w00=(1-fx)*(1-fy),w01=fx*(1-fy),w10=(1-fx)*fy,w11=fx*fy;\n')
        f.write('            float b=w00*p00[0]+w01*p01[0]+w10*p10[0]+w11*p11[0];\n')
        f.write('            float g=w00*p00[1]+w01*p01[1]+w10*p10[1]+w11*p11[1];\n')
        f.write('            float r=w00*p00[2]+w01*p01[2]+w10*p10[2]+w11*p11[2];\n')
        f.write('            float Y,U,V;\n')
        f.write('            bgr_to_yuv((unsigned char)b,(unsigned char)g,(unsigned char)r,&Y,&U,&V);\n')
        f.write('            int base=(dy*NN_IMG_W+dx)*3;\n')
        f.write('            out[base+0]=Y; out[base+1]=U; out[base+2]=V;\n')
        f.write('        }\n    }\n}\n\n')

        f.write('/* Forward pass */\n')
        f.write('int nn_predict(const unsigned char *img_bgr, int width, int height)\n{\n')
        f.write('    float x[NN_INPUT_SIZE];\n')
        f.write('    extract_features(img_bgr, width, height, x);\n\n')
        f.write('    /* Hidden layer: h = ReLU(W1 @ x + b1) */\n')
        f.write('    float h[NN_HIDDEN_SIZE];\n')
        f.write('    for (int i=0; i<NN_HIDDEN_SIZE; i++) {\n')
        f.write('        float sum=NN_b1[i];\n')
        f.write('        const float *w=NN_W1+i*NN_INPUT_SIZE;\n')
        f.write('        for (int j=0; j<NN_INPUT_SIZE; j++) sum+=w[j]*x[j];\n')
        f.write('        h[i]=sum>0.f?sum:0.f;\n')
        f.write('    }\n\n')
        f.write('    /* Output layer: argmax(W2 @ h + b2) */\n')
        f.write('    int best=0; float best_score=-1e30f;\n')
        f.write('    for (int i=0; i<NN_OUTPUT_SIZE; i++) {\n')
        f.write('        float sum=NN_b2[i];\n')
        f.write('        const float *w=NN_W2+i*NN_HIDDEN_SIZE;\n')
        f.write('        for (int j=0; j<NN_HIDDEN_SIZE; j++) sum+=w[j]*h[j];\n')
        f.write('        if (sum>best_score) { best_score=sum; best=i; }\n')
        f.write('    }\n')
        f.write('    return NN_CLASSES[best];\n}\n')

    print(f'Written: {predict_c}')
    print(f'\nDone. Classes exported: {cls_desc}')
    print(f'Turn-around label: {turn_label}')
    print(f'\nIn your drone code:')
    print(f'  #include "nn_predict.h"')
    print(f'  int dir = nn_predict(frame_bgr, w, h);')
    print(f'  /* {cls_desc} */')


if __name__ == '__main__':
    main()